concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Data Report Generator
on:
  push:
  schedule:
    - cron: '0 0 * * *'  # Run once a day at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        
      - name: Generate Report
        run: |
          mkdir -p docs
          bash .github/faithful-data-report.sh > docs/CAR-REPORT.md
          

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Old Faithful CAR data report update
          branch: 'gha-report'
          create_branch: true
          file_pattern: 'docs/*.md'

